### ISSUE TITLE
purefb_subnet does not support LAG parameter

### ISSUE THREAD

**Issue by gc-nathanh** [Pure-Storage-Ansible/FlashBlade-Collection#157]
**Describe the bug**
purefb_subnet module does not support the LAG parameter, which is required to create a new subnet

**To Reproduce**
1. attempt to create a subnet:
```
  - name: create a subnet ansible_test
    purestorage.flashblade.purefb_subnet:
      name: "ansible-test"
      mtu: 1500
      vlan: 1234
      prefix: 10.11.12.13/24
      gateway: 10.11.12.254
      state: present
      fb_url: localhost:8440
      api_token: <<token>
```

**Expected behavior**
The subnet should be created

**Output**
`    "msg": "Failed to create subnet ansible-test. Confirm supplied parameters"
`
**Desktop (please complete the following information):**
 - OS: macOS 11.5.2
 - Ansible: [core 2.11.4]
