### ISSUE TITLE
Invalid body parameter bucket_type in purefb_bucket module

### ISSUE THREAD

**Issue by krauthex** [Pure-Storage-Ansible/FlashBlade-Collection#249]
**Describe the bug**
I'd like to use the `purefb_bucket` module, which always fails with the error:  `"Object Store Bucket ansiblebucket creation failed. Error: Invalid body parameter: bucket_type"`, even with only the required minimum of options set:
```yaml
  - name: Create new bucket in s3 account.
    purestorage.flashblade.purefb_bucket:
      name: "{{ s3bucket.name }}"
      account: "{{ s3bucket.account }}"
      fb_url: "{{ flashblade_url }}"
      api_token: "{{ pure_token }}"
```
I see in the documentation [of the bucket module](https://docs.ansible.com/ansible/latest/collections/purestorage/flashblade/purefb_bucket_module.html#parameter-mode) that for the `mode`  option a Purity//FB version 3.3.3 is required. In my case we happen to have 3.3.2, so I assume this is where the issue arises. However, don't want to set the `mode` in the first place, but the module seems to nevertheless send the `bucket_type` option in the API call. 

**To Reproduce**
1. Install `purestorage.flashblade` collection (I used 1.14)
2. Have a flashblade with Purity//FB version < 3.3.3
3. Run the sample task above 
4. See error as described above

**Expected behavior**
If I don't set the `mode` option I'd assume that the task does not set a default value OR if there is a default value then there should be an option to disable the mode, if it only works with very recent Purity//FB versions.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04, python 3.9.7
 -  ansible-core 2.12.3, purestorage.flashblade collection 1.14.0

Let me know if you need additional info! :-)

**Comment by sdodsley** [comment]
@krauthex Please post the failure message when running the playbook with the `-vvvv` switch

**Comment by sdodsley** [comment]
@krauthex can you go to the following URL in a web-browser and post the output.
`https://<flashblade mgmt vip>/api/api_version`

**Comment by krauthex** [comment]
> @krauthex Please post the failure message when running the playbook with the `-vvvv` switch

Sure. :-) 
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "account": "ansibleprovisioner",
            "api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "default_retention": null,
            "eradicate": true,
            "fb_url": "REDACTED",
            "freeze_locked_objects": false,
            "hard_limit": null,
            "mode": "classic",
            "name": "ansiblebucket",
            "object_lock_enabled": false,
            "quota": null,
            "retention_lock": "unlocked",
            "retention_mode": null,
            "state": "present",
            "versioning": "absent"
        }
    },
    "msg": "Object Store Bucket ansiblebucket creation failed. Error: Invalid body parameter: bucket_type"
}
```

This is the error log when running the task:
```yaml
- name: Create new bucket in s3 account.
  purestorage.flashblade.purefb_bucket:
    name: "ansiblebucket"
    account: "ansibleprovisioner"
    eradicate: true
    fb_url: "{{ flashblade_url }}"
    api_token: "{{ pure_token }}"
```
