### ISSUE TITLE
Manage external certificates

### ISSUE THREAD

**Issue by Natscho2001** [Pure-Storage-Ansible/FlashBlade-Collection#282]
**Is your feature request related to a problem? Please describe.**
I would like to use my ansible role to manage external certificates

**Describe the solution you'd like**
Neither the purestorage.flashblade.purefb_certs nor the purestorage.flashblade.purefb_certgrp module provides the abilty to upload the CA Certificates as far as I understood the docs. From my point of view this could be part of purefb_certs module, however have this as an extra module is also fine.

**Comment by sdodsley** [comment]
@Natscho2001 you use `state: import` as detailed in this example:
```
- name: Import SSL Cert foo and Private Key
  purestorage.flashblade.purefb_certs:
    state: import
    name: foo
    certificate: "{{lookup('file', 'example.crt') }}"
    key: "{{lookup('file', 'example.key') }}"
    passphrase: password
    fb_url: 10.10.10.2
    api_token: T-55a68eb5-c785-4720-a2ca-8b03903bf641
```
