### ISSUE TITLE
pypureclient SDK is required for this module

### ISSUE THREAD

**Issue by JoshuaHaus** [Pure-Storage-Ansible/FlashBlade-Collection#301]
**Describe the bug**
While Using purestorage.flashblade.purefb_ra with enasible the task fails with the error pypureclient SDK is required for this module.
We use a delegation Host and we use the parameter become: true

We have tried to run this Task with the python interpreter 3.9 and 3.11 for both interpreters the pypureclient is installed in the version 1.55.0 pypureclient some other versions of pypureclient has been tested as well. the error message was the same.

**To Reproduce**
1. Create a playbook to open Remote Assist
2. install pypureclient for python 3.9 or python 3.11
3. run the Playbook in python 3.9 or python 3.11

**Expected behavior**
A Remote Assist on the selected array is open

**Screenshots**
![image](https://github.com/user-attachments/assets/c8d38c5e-be60-4855-b38a-b23deba8a5dc)
![image](https://github.com/user-attachments/assets/46f7bb31-7a98-4f5e-89ef-8cd3695f0664)

**Comment by JoshuaHaus** [comment]
The used collection has the Version 1.18.0

**Comment by sdodsley** [comment]
@JoshuaHaus because you are delegating to another host, that host must have all the FlashBlade Collection pre-requisites installed, including `py-pure-client`. As you are using `become` then the pre-reqs must also be accessible by the `become` user.
I suggest you issue a task early on in your playbook something like:

```
  - name: Install FlashBlade Collection pre-reqs
    delegate_to: <host>
    become: true
    pip:
      name:
        - netaddr
        - datetime
        - pycountry
        - pytz
        - purity-fb
        - py-pure-client
        - urllib3
```
