### ISSUE TITLE
Unable to import our root CA Certs

### ISSUE THREAD

**Issue by tdevos-ROSEN** [Pure-Storage-Ansible/FlashBlade-Collection#303]
**Describe the bug**
I want to manage our trusted root CAs with the ansible role, manually I would use this interface on the FlashBlade

![image](https://github.com/user-attachments/assets/f3094de6-e317-428b-aa71-fcfb3eb3624a)

**To Reproduce**
I created a task which should loop through our (Sub)CA Certs and upload them

```yaml
- name: FlashBlade > FlashBlade basic> Upload trusted root certs
  purestorage.flashblade.purefb_certs:
    state: import
    name: "{{ certificate | splitext | first}}"
    certificate: "{{lookup('file', '{{ certificate }}') }}"
    fb_url: "{{ inventory_hostname }}"
    api_token: "{{ api_token_obj.result.Content }}"
  tags: certificate
  delegate_to: localhost
  loop: "{{ certs | default([]) }}"
  loop_control:
    loop_var: certificate
```

Where certs looks like this:

```yaml
certs:
  - subca.pem
  - root.pem
  - anothersubca.pem
```

But the playbook stops with:

```bash
TASK [flashblade_management : FlashBlade > FlashBlade basic> Upload trusted root certs] ***
failed: [houfb10 -> localhost] (item=subca.pem) => {"ansible_loop_var": "certificate", "certificate": "subca.pem", "changed": false, "msg": "Importing Certificate failed. Error: One or more read-only field(s) is included."}
failed: [houfb10 -> localhost] (item=root.pem) => {"ansible_loop_var": "certificate", "certificate": "root.pem", "changed": false, "msg": "Importing Certificate failed. Error: One or more read-only field(s) is included."}
failed: [houfb10 -> localhost] (item=anothersub.pem) => {"ansible_loop_var": "certificate", "certificate": "anothersubca.pem", "changed": false, "msg": "Importing Certificate failed. Error: One or more read-only field(s) is included."}
```

**Expected behavior**
The ca certs should appear under external certifcates to validate e.g. S3 connections.

The documentation says for import "import will import a CA provided certificate.". Do I am using the right module to perform the task?

**Comment by tdevos-ROSEN** [comment]
Collection             Version
---------------------- -------
ansible.posix          1.5.4
community.general      9.3.0
community.mysql        3.7.2
community.okd          2.3.0
community.vmware       3.7.0
cyberark.pas           1.0.27
kubernetes.core        2.4.0
purestorage.flasharray 1.31.1
purestorage.flashblade 1.18.0

**Comment by sdodsley** [comment]
You are using the correct module.

We need to investigate what is causing this error.

**Comment by sdodsley** [comment]
@tdevos-ROSEN sorry for taking so long to get back to you on this.
The specific error is `Error: One or more read-only field(s) is included.`. 
Is there any way you can tell us what all the fields were you used when creating the cert?
It looks like one (or more) of these is causing a bad response from the underlying SDK.

**Comment by tdevos-ROSEN** [comment]
Hi Simon,

I can try, not sure what you are expecting.

At first I download our root ca in the pipeline:

```bash
curl -o CA1.pem http://crl/CA1.pem
curl -o CA2.pem http://crl/CA2.pem
curl -o CA3.pem http://crl/CA3.pem
```

In the playbook I try to upload them to the flashblades

```yaml
- name: FlashBlade > FlashBlade basic> Upload trusted root certs
  purestorage.flashblade.purefb_certs:
    state: import
    name: "{{ certificate | splitext | first}}"
    certificate: "{{lookup('file', '{{ certificate }}') }}"
    fb_url: "{{ inventory_hostname }}"
    api_token: "{{ api_token_obj.result.Content }}"
  tags: certificate
  delegate_to: localhost
  loop: "{{ certs | default([]) }}"
  loop_control:
    loop_var: certificate
```

And here the verbose output of the task

```yaml
failed: [FLASHBLADE -> localhost] (item=CA1.pem) => {
    "ansible_loop_var": "certificate",
    "certificate": "CA1.pem",
    "changed": false,
    "invocation": {
        "module_args": {
            "api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "certificate": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "common_name": null,
            "country": null,
            "days": 3650,
            "disable_warnings": false,
            "email": null,
            "export_file": null,
            "fb_url": "FLASHBLADE",
            "generate": false,
            "intermeadiate_cert": null,
            "key": null,
            "key_size": 2048,
            "locality": null,
            "name": "CA1",
            "org_unit": null,
            "organization": null,
            "passphrase": null,
            "province": null,
            "state": "import"
        }
    },
    "msg": "Importing Certificate failed. Error: One or more read-only field(s) is included."
}
```

As said, I don't want to create a certificate for the flashblade itself, I just want to upload our CA certs so that our S3 requests don't get an certifacte error (because the flashblade does not trust our CAs) or we need to disable ssl verfiy in our requests.

the manueal step is like this
![image](https://github.com/user-attachments/assets/e8f22862-2b33-42d5-8696-e295d325bd6a)
![image](https://github.com/user-attachments/assets/e3cb52c8-f584-49df-af46-e9d6b5e8a0b8)
