### ISSUE TITLE
Filesystems Configuration Snapshots

### ISSUE THREAD

**Issue by nbarriere** [Pure-Storage-Ansible/FlashBlade-Collection#325]
Hello,

I would like to apply three snapshots policy to fs: hourly, daily and weekly.

Only the first item in the list is applied. How I can apply multiple snapshots policies on a fs?

There is also a bug when I remove the first item of the list, it's not remove from the configuration, maybe it's related to the first issue.

```

---
- name: Pure FlashBlade Filesystems Configuration
  hosts: localhost
  collections:
    - purestorage.flashblade
  vars:
    fb_url: nas.xxx.net
    fb_api_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  tasks:
    - name: Filesystem - test_ansible
      purestorage.flashblade.purefb_fs:
        name: test_ansible
        access_control: shared
        client_policy: ""
        export_policy: ""
        nfs_rules: ""
       	policy: "hourly, daily, weekly"
        policy_state: present
        size: 1T
        hard_limit: False
        nfsv3: True
        nfsv4: True
        http: False
        smb: False
        snapshot: True
        fastremove: False
        writable: True
        state: present
        fb_url: "{{ fb_url }}"
        api_token: "{{ fb_api_token }}"
        disable_warnings: True

```

Versions:

FlashBlade//S Multi-chassis: 4.3.8

purestorage.flashblade:1.19.1
```

/usr/src/app # pip freeze
ansible==10.5.0
ansible-core==2.17.6
bcrypt==4.2.0
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.4.0
cryptography==43.0.3
DateTime==5.5
distro==1.9.0
idna==3.10
Jinja2==3.1.4
MarkupSafe==3.0.2
netaddr==1.3.0
packaging==24.1
paramiko==3.5.0
purity-fb==1.12.3
py-pure-client==1.56.0
pycparser==2.22
PyJWT==2.9.0
PyNaCl==1.5.0
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
pytz==2024.2
PyYAML==6.0.2
requests==2.32.3
resolvelib==1.0.1
setuptools==75.3.0
six==1.16.0
urllib3==2.2.3
wheel==0.43.0
zope.interface==7.1.1

```
