### ISSUE TITLE
flashblade.purefb_dns errors out on KeyError: 'service'

### ISSUE THREAD

**Issue by mdkent** [Pure-Storage-Ansible/FlashBlade-Collection#363]
**Describe the bug**
After bumping to 1.20.0 we're seeing a failure in the flashblade.purefb_dns module. This was fine on 1.19.2.

It fails with 

> in main\n  File \"/var/folders/f1/_00jhynx1x59dkrpk2g2f4mc0000gn/T/ansible_purestorage.flashblade.purefb_dns_payload_76cteant/ansible_purestorage.flashblade.purefb_dns_payload.zip/ansible_collections/purestorage/flashblade/plugins/modules/purefb_dns.py\", line 172, in update_multi_dns\nKeyError: 'service'\n"

[Exact line](https://github.com/Pure-Storage-Ansible/FlashBlade-Collection/blob/20e4c8b9dac0f515e5b1e3af9f501b4c3ba778f6/plugins/modules/purefb_dns.py#L172).

**To Reproduce**
```
    - name: "{{ datacenter }} - DNS servers"
      purestorage.flashblade.purefb_dns:
        fb_url: "{{ fb_url }}"
        api_token: "{{ api_token }}"
        domain: foo.com
        nameservers:
          - 10.0.0.1
```
Looking at the code, it looks like `module.params["service"]` isn't given a default value in `main()`. 

I tried fixing it but I'm a bit confused on what the value should be as the API looks to expect a list of services like `management, data`.
