### ISSUE TITLE
purestorage.flashblade.purefb_lifecycle - can't set a standalone abort_uploads_after rule

### ISSUE THREAD

**Issue by mdkent** [Pure-Storage-Ansible/FlashBlade-Collection#372]
**Describe the bug**
Using `purestorage.flashblade.purefb_lifecycle` we're unable to set a lifecycle rule that **only** sets a `abort_uploads_after` setting, we're forced to set a `keep_*` value. 

When using the Pure UI, we're able to create a standalone `abort_uploads_after` rule just fine.

This is limiting us as we want to add a default `abort_uploads_after` rule for all buckets, without considering a `keep_*` setting.

**To Reproduce**

Given a task like:
```yaml
- name: "Test lifecycle rules"
  hosts: localhost
  tasks:
    - name: "Demo"
      purestorage.flashblade.purefb_lifecycle:
        fb_url: "{{ fb_url }}"
        api_token: "{{ api_token }}"
        name: "abort-uploads-after-1d"
        bucket: "logging-staging-elasticsearch-snapshots"
        abort_uploads_after: "1d"
```
it will fail with:
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "abort_uploads_after": "1d",
            "api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "bucket": "logging-staging-elasticsearch-snapshots",
            "disable_warnings": false,
            "enabled": true,
            "fb_url": "10.10.4.1",
            "keep_current_for": null,
            "keep_current_until": null,
            "keep_previous_for": null,
            "name": "abort-uploads-after-1d",
            "prefix": null,
            "state": "present"
        }
    },
    "msg": "At least one `keep...` parameter is required to create a new lifecycle rule"
}
```
while in the UI I can create this fine:

<img width="1656" alt="Image" src="https://github.com/user-attachments/assets/918f79b6-7abd-4943-98d4-031a78841977" />

**Expected behavior**
No we should be able to set a rule with only `abort_uploads_after`.

**Additional context**
Using `py-pure-client==1.67.2`
Using 
```yaml
collections:
  - name: https://github.com/Pure-Storage-Ansible/FlashBlade-Collection
    type: git
    version: 6050b18102b356328dcca6c5d62886668ae269c0
```
